# Generated by Django 4.2.5 on 2023-09-12 23:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.IntegerField(max_length=60)),
                ('tiempo_vuelo_en_horas', models.IntegerField(max_length=2, validators=[django.core.validators.MinValueValidator(1, message='El tiempo mínimo de vuelo es 1 hora.'), django.core.validators.MaxValueValidator(19, message='El vuelo más largo posible es de 19 horas.')])),
            ],
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('tipo_licencia', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El nivel mínimo debe ser 1.'), django.core.validators.MaxValueValidator(4, message='El nivel máximo debe ser 4.')])),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAerolinea.aerolinea')),
            ],
        ),
        migrations.CreateModel(
            name='Avion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(max_length=12)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppAerolinea.aerolinea')),
            ],
        ),
        migrations.AddField(
            model_name='aerolinea',
            name='destinos',
            field=models.ManyToManyField(to='AppAerolinea.destino'),
        ),
    ]
