# Generated by Django 4.2.5 on 2023-09-13 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAerolinea', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aerolinea',
            options={'verbose_name': 'Airline', 'verbose_name_plural': 'Airlines'},
        ),
        migrations.AlterModelOptions(
            name='avion',
            options={'verbose_name': 'Plane', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterModelOptions(
            name='destino',
            options={'verbose_name': 'Destiny', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='piloto',
            options={'verbose_name': 'Pilot', 'verbose_name_plural': 'Pilots'},
        ),
        migrations.RemoveField(
            model_name='aerolinea',
            name='destinos',
        ),
        migrations.AlterField(
            model_name='aerolinea',
            name='nombre',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='destino',
            name='nombre',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='destino',
            name='tiempo_vuelo_en_horas',
            field=models.IntegerField(max_length=2, validators=[django.core.validators.MinValueValidator(1, message='El tiempo mínimo de vuelo es 1 hora.'), django.core.validators.MaxValueValidator(24, message='El vuelo más largo posible es de 19 horas.')]),
        ),
    ]
