# Generated by Django 4.2.5 on 2023-09-13 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAerolinea', '0002_alter_aerolinea_options_alter_avion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piloto',
            name='aerolinea',
        ),
    ]
