# Generated by Django 4.2.5 on 2023-09-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAerolinea', '0003_remove_piloto_aerolinea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avion',
            name='fecha_fabricacion',
        ),
    ]
