# Generated by Django 4.2.5 on 2023-09-14 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAerolinea', '0004_remove_avion_fecha_fabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='tiempo_vuelo_en_horas',
            field=models.IntegerField(max_length=2, validators=[django.core.validators.MinValueValidator(1, message='El tiempo mínimo de vuelo es 1 hora.'), django.core.validators.MaxValueValidator(30, message='El vuelo más largo posible es de 30 horas.')]),
        ),
    ]
